{"name": "Scenario", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=58203): Max retries exceeded with url: /session/817ab8dc2f5bc728649352dde1ee50c5/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002DE2B4486B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "trace": "  File \"C:\\Users\\ttravis\\OneDrive - QA Consultants\\Desktop\\TrainingProject\\.env\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\ttravis\\OneDrive - QA Consultants\\Desktop\\TrainingProject\\.env\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\steps.py\", line 62, in step_impl\n    context.driver.get(\"https://www.automationexercise.com/products\")\n  File \"C:\\Users\\ttravis\\OneDrive - QA Consultants\\Desktop\\TrainingProject\\.env\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 356, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"C:\\Users\\ttravis\\OneDrive - QA Consultants\\Desktop\\TrainingProject\\.env\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 345, in execute\n    response = self.command_executor.execute(driver_command, params)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\ttravis\\OneDrive - QA Consultants\\Desktop\\TrainingProject\\.env\\Lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 302, in execute\n    return self._request(command_info[0], url, body=data)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\ttravis\\OneDrive - QA Consultants\\Desktop\\TrainingProject\\.env\\Lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 322, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\ttravis\\OneDrive - QA Consultants\\Desktop\\TrainingProject\\.env\\Lib\\site-packages\\urllib3\\_request_methods.py\", line 144, in request\n    return self.request_encode_body(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\ttravis\\OneDrive - QA Consultants\\Desktop\\TrainingProject\\.env\\Lib\\site-packages\\urllib3\\_request_methods.py\", line 279, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\ttravis\\OneDrive - QA Consultants\\Desktop\\TrainingProject\\.env\\Lib\\site-packages\\urllib3\\poolmanager.py\", line 444, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\ttravis\\OneDrive - QA Consultants\\Desktop\\TrainingProject\\.env\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 877, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\ttravis\\OneDrive - QA Consultants\\Desktop\\TrainingProject\\.env\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 877, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\ttravis\\OneDrive - QA Consultants\\Desktop\\TrainingProject\\.env\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 877, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\ttravis\\OneDrive - QA Consultants\\Desktop\\TrainingProject\\.env\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 847, in urlopen\n    retries = retries.increment(\n              ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\ttravis\\OneDrive - QA Consultants\\Desktop\\TrainingProject\\.env\\Lib\\site-packages\\urllib3\\util\\retry.py\", line 515, in increment\n    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "steps": [{"name": "Given I am on the login page", "status": "passed", "start": 1716490654188, "stop": 1716490658139}, {"name": "When I log in with valid credentials", "status": "passed", "start": 1716490658139, "stop": 1716490666824}, {"name": "Then I should see the delete account link", "status": "passed", "start": 1716490666824, "stop": 1716490671653}, {"name": "Then I will go to the products page", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=58203): Max retries exceeded with url: /session/817ab8dc2f5bc728649352dde1ee50c5/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002DE2B4486B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "trace": "  File \"C:\\Users\\ttravis\\OneDrive - QA Consultants\\Desktop\\TrainingProject\\.env\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\ttravis\\OneDrive - QA Consultants\\Desktop\\TrainingProject\\.env\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\steps.py\", line 62, in step_impl\n    context.driver.get(\"https://www.automationexercise.com/products\")\n  File \"C:\\Users\\ttravis\\OneDrive - QA Consultants\\Desktop\\TrainingProject\\.env\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 356, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"C:\\Users\\ttravis\\OneDrive - QA Consultants\\Desktop\\TrainingProject\\.env\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 345, in execute\n    response = self.command_executor.execute(driver_command, params)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\ttravis\\OneDrive - QA Consultants\\Desktop\\TrainingProject\\.env\\Lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 302, in execute\n    return self._request(command_info[0], url, body=data)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\ttravis\\OneDrive - QA Consultants\\Desktop\\TrainingProject\\.env\\Lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 322, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\ttravis\\OneDrive - QA Consultants\\Desktop\\TrainingProject\\.env\\Lib\\site-packages\\urllib3\\_request_methods.py\", line 144, in request\n    return self.request_encode_body(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\ttravis\\OneDrive - QA Consultants\\Desktop\\TrainingProject\\.env\\Lib\\site-packages\\urllib3\\_request_methods.py\", line 279, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\ttravis\\OneDrive - QA Consultants\\Desktop\\TrainingProject\\.env\\Lib\\site-packages\\urllib3\\poolmanager.py\", line 444, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\ttravis\\OneDrive - QA Consultants\\Desktop\\TrainingProject\\.env\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 877, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\ttravis\\OneDrive - QA Consultants\\Desktop\\TrainingProject\\.env\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 877, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\ttravis\\OneDrive - QA Consultants\\Desktop\\TrainingProject\\.env\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 877, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\ttravis\\OneDrive - QA Consultants\\Desktop\\TrainingProject\\.env\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 847, in urlopen\n    retries = retries.increment(\n              ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\ttravis\\OneDrive - QA Consultants\\Desktop\\TrainingProject\\.env\\Lib\\site-packages\\urllib3\\util\\retry.py\", line 515, in increment\n    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1716490671654, "stop": 1716490688289}], "start": 1716490654180, "stop": 1716490688314, "uuid": "1102bb9c-c8ca-4f7e-a7c9-4124960d977b", "historyId": "77ad07d4c6158b3d6991f51fccf9ce60", "fullName": "Online Shopping Testing: Scenario", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "productsTest"}, {"name": "feature", "value": "Online Shopping Testing"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}